services:
  - type: web
    name: ar-builders-backend
    env: docker
    dockerContext: backend
    dockerfilePath: backend/Dockerfile
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
